attributes:
  X1 Relative_Compactness
  X2 Surface_Area
  X3 Wall_Area
  X4 Roof_Area
  X5 Overall_Height
  X6 Orientation
  X7 Glazing_Area
  X8 Glazing_Area_Distribution
  y1 Heating_Load
  y2 Cooling_Load
 
columns:
  Relative_Compactness: float
  Surface_Area: float
  Wall_Area: float
  Roof_Area: float
  Overall_Height: float
  Orientation: int
  Glazing_Area: float
  Glazing_Area_Distribution: int
  Heating_Load: float
  Cooling_Load: float

target_columns: [Heating_Load, Cooling_Load]

target_column_1: 
  - Heating_Load

target_column_2:
  - Cooling_Load

numerical_columns:
  - Relative_Compactness         
  - Surface_Area
  - Wall_Area
  - Roof_Area
  - Overall_Height
  - Orientation
  - Glazing_Area
  - Glazing_Area_Distribution